package com.example.vmac.callCenter.rcms;

public class CallInfoEntity {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column call_info.id
     *
     * @mbggenerated Wed Nov 15 09:54:a33 CST 2017
     */
    private Integer id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column call_info.call_no
     *
     * @mbggenerated Wed Nov 15 09:54:a33 CST 2017
     */
    private String callNo;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column call_info.customer_address
     *
     * @mbggenerated Wed Nov 15 09:54:a33 CST 2017
     */
    private String customerAddress;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column call_info.enduser
     *
     * @mbggenerated Wed Nov 15 09:54:a33 CST 2017
     */
    private String enduser;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column call_info.customer_name
     *
     * @mbggenerated Wed Nov 15 09:54:a33 CST 2017
     */
    private String customerName;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column call_info.telephone
     *
     * @mbggenerated Wed Nov 15 09:54:a33 CST 2017
     */
    private String telephone;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column call_info.customer_number
     *
     * @mbggenerated Wed Nov 15 09:54:a33 CST 2017
     */
    private String customerNumber;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column call_info.machine_type
     *
     * @mbggenerated Wed Nov 15 09:54:a33 CST 2017
     */
    private String machineType;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column call_info.machine_sn
     *
     * @mbggenerated Wed Nov 15 09:54:a33 CST 2017
     */
    private String machineSn;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column call_info.ibm_engineer
     *
     * @mbggenerated Wed Nov 15 09:54:a33 CST 2017
     */
    private String ibmEngineer;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column call_info.ibm_engeineer_sn
     *
     * @mbggenerated Wed Nov 15 09:54:a33 CST 2017
     */
    private String ibmEngeineerSn;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column call_info.engineer_telephone
     *
     * @mbggenerated Wed Nov 15 09:54:a33 CST 2017
     */
    private String engineerTelephone;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column call_info.contacts
     *
     * @mbggenerated Wed Nov 15 09:54:a33 CST 2017
     */
    private String contacts;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column call_info.fault_part
     *
     * @mbggenerated Wed Nov 15 09:54:a33 CST 2017
     */
    private String faultPart;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column call_info.remark
     *
     * @mbggenerated Wed Nov 15 09:54:a33 CST 2017
     */
    private String remark;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column call_info.level
     *
     * @mbggenerated Wed Nov 15 09:54:a33 CST 2017
     */
    private Integer level;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column call_info.fault_detail
     *
     * @mbggenerated Wed Nov 15 09:54:a33 CST 2017
     */
    private String faultDetail;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column call_info.machine_model
     *
     * @mbggenerated Wed Nov 15 09:54:a33 CST 2017
     */
    private String machineModel;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column call_info.id
     *
     * @return the value of call_info.id
     *
     * @mbggenerated Wed Nov 15 09:54:a33 CST 2017
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column call_info.id
     *
     * @param id the value for call_info.id
     *
     * @mbggenerated Wed Nov 15 09:54:a33 CST 2017
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column call_info.call_no
     *
     * @return the value of call_info.call_no
     *
     * @mbggenerated Wed Nov 15 09:54:a33 CST 2017
     */
    public String getCallNo() {
        return callNo;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column call_info.call_no
     *
     * @param callNo the value for call_info.call_no
     *
     * @mbggenerated Wed Nov 15 09:54:a33 CST 2017
     */
    public void setCallNo(String callNo) {
        this.callNo = callNo;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column call_info.customer_address
     *
     * @return the value of call_info.customer_address
     *
     * @mbggenerated Wed Nov 15 09:54:a33 CST 2017
     */
    public String getCustomerAddress() {
        return customerAddress;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column call_info.customer_address
     *
     * @param customerAddress the value for call_info.customer_address
     *
     * @mbggenerated Wed Nov 15 09:54:a33 CST 2017
     */
    public void setCustomerAddress(String customerAddress) {
        this.customerAddress = customerAddress;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column call_info.enduser
     *
     * @return the value of call_info.enduser
     *
     * @mbggenerated Wed Nov 15 09:54:a33 CST 2017
     */
    public String getEnduser() {
        return enduser;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column call_info.enduser
     *
     * @param enduser the value for call_info.enduser
     *
     * @mbggenerated Wed Nov 15 09:54:a33 CST 2017
     */
    public void setEnduser(String enduser) {
        this.enduser = enduser;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column call_info.customer_name
     *
     * @return the value of call_info.customer_name
     *
     * @mbggenerated Wed Nov 15 09:54:a33 CST 2017
     */
    public String getCustomerName() {
        return customerName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column call_info.customer_name
     *
     * @param customerName the value for call_info.customer_name
     *
     * @mbggenerated Wed Nov 15 09:54:a33 CST 2017
     */
    public void setCustomerName(String customerName) {
        this.customerName = customerName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column call_info.telephone
     *
     * @return the value of call_info.telephone
     *
     * @mbggenerated Wed Nov 15 09:54:a33 CST 2017
     */
    public String getTelephone() {
        return telephone;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column call_info.telephone
     *
     * @param telephone the value for call_info.telephone
     *
     * @mbggenerated Wed Nov 15 09:54:a33 CST 2017
     */
    public void setTelephone(String telephone) {
        this.telephone = telephone;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column call_info.customer_number
     *
     * @return the value of call_info.customer_number
     *
     * @mbggenerated Wed Nov 15 09:54:a33 CST 2017
     */
    public String getCustomerNumber() {
        return customerNumber;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column call_info.customer_number
     *
     * @param customerNumber the value for call_info.customer_number
     *
     * @mbggenerated Wed Nov 15 09:54:a33 CST 2017
     */
    public void setCustomerNumber(String customerNumber) {
        this.customerNumber = customerNumber;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column call_info.machine_type
     *
     * @return the value of call_info.machine_type
     *
     * @mbggenerated Wed Nov 15 09:54:a33 CST 2017
     */
    public String getMachineType() {
        return machineType;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column call_info.machine_type
     *
     * @param machineType the value for call_info.machine_type
     *
     * @mbggenerated Wed Nov 15 09:54:a33 CST 2017
     */
    public void setMachineType(String machineType) {
        this.machineType = machineType;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column call_info.machine_sn
     *
     * @return the value of call_info.machine_sn
     *
     * @mbggenerated Wed Nov 15 09:54:a33 CST 2017
     */
    public String getMachineSn() {
        return machineSn;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column call_info.machine_sn
     *
     * @param machineSn the value for call_info.machine_sn
     *
     * @mbggenerated Wed Nov 15 09:54:a33 CST 2017
     */
    public void setMachineSn(String machineSn) {
        this.machineSn = machineSn;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column call_info.ibm_engineer
     *
     * @return the value of call_info.ibm_engineer
     *
     * @mbggenerated Wed Nov 15 09:54:a33 CST 2017
     */
    public String getIbmEngineer() {
        return ibmEngineer;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column call_info.ibm_engineer
     *
     * @param ibmEngineer the value for call_info.ibm_engineer
     *
     * @mbggenerated Wed Nov 15 09:54:a33 CST 2017
     */
    public void setIbmEngineer(String ibmEngineer) {
        this.ibmEngineer = ibmEngineer;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column call_info.ibm_engeineer_sn
     *
     * @return the value of call_info.ibm_engeineer_sn
     *
     * @mbggenerated Wed Nov 15 09:54:a33 CST 2017
     */
    public String getIbmEngeineerSn() {
        return ibmEngeineerSn;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column call_info.ibm_engeineer_sn
     *
     * @param ibmEngeineerSn the value for call_info.ibm_engeineer_sn
     *
     * @mbggenerated Wed Nov 15 09:54:a33 CST 2017
     */
    public void setIbmEngeineerSn(String ibmEngeineerSn) {
        this.ibmEngeineerSn = ibmEngeineerSn;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column call_info.engineer_telephone
     *
     * @return the value of call_info.engineer_telephone
     *
     * @mbggenerated Wed Nov 15 09:54:a33 CST 2017
     */
    public String getEngineerTelephone() {
        return engineerTelephone;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column call_info.engineer_telephone
     *
     * @param engineerTelephone the value for call_info.engineer_telephone
     *
     * @mbggenerated Wed Nov 15 09:54:a33 CST 2017
     */
    public void setEngineerTelephone(String engineerTelephone) {
        this.engineerTelephone = engineerTelephone;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column call_info.contacts
     *
     * @return the value of call_info.contacts
     *
     * @mbggenerated Wed Nov 15 09:54:a33 CST 2017
     */
    public String getContacts() {
        return contacts;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column call_info.contacts
     *
     * @param contacts the value for call_info.contacts
     *
     * @mbggenerated Wed Nov 15 09:54:a33 CST 2017
     */
    public void setContacts(String contacts) {
        this.contacts = contacts;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column call_info.fault_part
     *
     * @return the value of call_info.fault_part
     *
     * @mbggenerated Wed Nov 15 09:54:a33 CST 2017
     */
    public String getFaultPart() {
        return faultPart;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column call_info.fault_part
     *
     * @param faultPart the value for call_info.fault_part
     *
     * @mbggenerated Wed Nov 15 09:54:a33 CST 2017
     */
    public void setFaultPart(String faultPart) {
        this.faultPart = faultPart;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column call_info.remark
     *
     * @return the value of call_info.remark
     *
     * @mbggenerated Wed Nov 15 09:54:a33 CST 2017
     */
    public String getRemark() {
        return remark;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column call_info.remark
     *
     * @param remark the value for call_info.remark
     *
     * @mbggenerated Wed Nov 15 09:54:a33 CST 2017
     */
    public void setRemark(String remark) {
        this.remark = remark;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column call_info.level
     *
     * @return the value of call_info.level
     *
     * @mbggenerated Wed Nov 15 09:54:a33 CST 2017
     */
    public Integer getLevel() {
        return level;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column call_info.level
     *
     * @param level the value for call_info.level
     *
     * @mbggenerated Wed Nov 15 09:54:a33 CST 2017
     */
    public void setLevel(Integer level) {
        this.level = level;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column call_info.fault_detail
     *
     * @return the value of call_info.fault_detail
     *
     * @mbggenerated Wed Nov 15 09:54:a33 CST 2017
     */
    public String getFaultDetail() {
        return faultDetail;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column call_info.fault_detail
     *
     * @param faultDetail the value for call_info.fault_detail
     *
     * @mbggenerated Wed Nov 15 09:54:a33 CST 2017
     */
    public void setFaultDetail(String faultDetail) {
        this.faultDetail = faultDetail;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column call_info.machine_model
     *
     * @return the value of call_info.machine_model
     *
     * @mbggenerated Wed Nov 15 09:54:a33 CST 2017
     */
    public String getMachineModel() {
        return machineModel;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column call_info.machine_model
     *
     * @param machineModel the value for call_info.machine_model
     *
     * @mbggenerated Wed Nov 15 09:54:a33 CST 2017
     */
    public void setMachineModel(String machineModel) {
        this.machineModel = machineModel;
    }
}